# Generated by Django 4.2.1 on 2023-06-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_blogs_db_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='blogs_db',
            name='subtitle',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='blogs_db',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
